url: https://barcamp-bayamon.github.io
baseurl:

# Site settings
title: Barcamp Bayamon
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Axel Rivera
  pic: img/arivera.jpg
  position: The Reasonable One
  social:
    - title: twitter
      url: https://twitter.com/arivera

- name: Froilán Irizarry
  pic: img/froi.jpg
  position: The Hammer
  social:
    - title: twitter
      url: https://twitter.com/skfroi

- name: Luis Armando Torres
  pic: img/luis_torres.png
  position: Purveyor of Things
  social:
    - title: twitter
      url: https://twitter.com/engine4cws

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/barcampbayamon
  - title: facebook
    url: https://www.facebook.com/barcampbayamon/
  - title: github
    url: https://github.com/barcamp-bayamon
  - title: instagram
    url: https://www.instagram.com/barcampbayamon/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

sponsors:
  row1:
    - name: engine-4
      url: http://engine-4.com
      img_url: img/logos/engine-4-official-logo-2016.png
      css_class: img-responsive img-circle sponsors-img-width
    - name: Municipio de Bayamon
      url: http://www.municipiodebayamon.com/
      img_url: http://imgur.com/zu5tfVF.jpg
      css_class: img-responsive sponsors-img-width
    - name: Parallel 18
      url: http://parallel18.com/
      img_url: img/logos/parallel18-black-w-name.png
      css_class: img-responsive
    - name: Puerto Rico Science, Technology, and Research Trust
      url: http://prsciencetrust.org/
      img_url: img/logos/prst-logo.png
      css_class: img-responsive
  row2:
    - name: Ricardo Muñiz
      url: https://twitter.com/rickymunizjr
      img_url: https://pbs.twimg.com/profile_images/595776446678851585/ozkRwxzs.jpg
      css_class: img-responsive img-circle sponsors-img-width
    - name: James Lynn
      url: https://twitter.com/jameslynn
      img_url: https://pbs.twimg.com/profile_images/2519791387/m4ek5mye3ai134zmcxn0.jpeg
      css_class: img-responsive img-circle sponsors-img-width
    - name: Luis Figarella
      url: https://www.linkedin.com/in/luis-figarella-351197
      img_url: http://i.imgur.com/9pE9I1i.jpg
      css_class: img-responsive img-circle sponsors-img-width
# Build settings
markdown: kramdown
permalink: pretty
